apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: nc
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: NodePort