apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nc
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: nginx
  type: NodePort