apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: nc
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: charleslucloud/nginx:stable-alpine-armv7
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nextcloud
          mountPath: /var/www/html
        ports:
        - containerPort: 80
      volumes:
      - name: conf
        configMap:
          name: nginx-conf-cm
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nc
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: nginx
  type: NodePort