apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-ingressroute
  namespace: nc
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`nextcloud.charleslu.me`)
    services:
    - name: nginx-svc
      port: 80
