apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nextcloud-svc
  labels:
    app: nextcloud
spec:
  ports:
  - port: 9000
    targetPort: {{ .Values.deployment.nextcloud.targetPort }}
    protocol: TCP
  selector:
    app: nextcloud