apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      {{- with .Values.deployment.nginx }}
      - name: {{ .name }}
        image: {{ .image }}
        imagePullPolicy: {{ .imagePullPolicy }}
      {{- end }}
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nextcloud
          mountPath: /var/www/html
        ports:
        - containerPort: 80
      volumes:
      - name: conf
        configMap:
          name: nginx-conf-cm
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: nextcloud
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-nextcloud-pvc