apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
  labels:
    app: postgres
spec:
  storageClassName: pv1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.resources.storage.postgres.pgdata }}
  selector:
    matchLabels:
      app: postgres