apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: nc
  labels:
    app: postgres
spec:
  storageClassName: pv2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/k3s/pgdata"
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: nc
  labels:
    app: postgres
spec:
  storageClassName: pv2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: postgres