apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: nc
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine-armv7
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_DB
          value: psqldb
        - name: POSTGRES_USER
          value: postgres
        #- name: POSTGRES_HOST
        #  value: 127.0.0.1
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
            #kubectl create secret generic postgres-passwd --from-literal=password=system123 -n nc
              name: postgres-passwd
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: nc
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres