apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deploy
  namespace: nc
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox:1.31.1
        command: ["chmod", "777", "/var/www/html"]
        volumeMounts:
          - name: nextcloud
            mountPath: /var/www/html
      containers:
      - name: nextcloud
        image: nextcloud@sha256:3b10d9e24f2511161b2c1a91c74462073324b2053f67967fde0964231af168f0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nextcloud
          mountPath: /var/www/html
        - name: apps
          mountPath: /var/www/html/custom_apps
        - name: config
          mountPath: /var/www/html/config
        - name: data
          mountPath: /var/www/html/data
        ports:
        - containerPort: 9000
      volumes:
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud-pvc
      - name: apps
        persistentVolumeClaim:
          claimName: nextcloud-apps-pvc
      - name: config
        persistentVolumeClaim:
          claimName: nextcloud-config-pvc
      - name: data
        persistentVolumeClaim:
          claimName: nextcloud-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-svc
  namespace: nc
  labels:
    app: nextcloud
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: nextcloud