apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  namespace: nc
  labels:
    app: nextcloud
spec:
  storageClassName: pv1
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/k3s/nextcloud"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nc
  labels:
    app: nextcloud
spec:
  storageClassName: pv1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: nextcloud
