apiVersion: v1
kind: Service
metadata:
  name: nextcloud-svc
  namespace: nc
  labels:
    app: nextcloud
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: nextcloud