apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
  namespace: nc
  labels:
    app: nextcloud
spec:
  storageClassName: pv1
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/k3s/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nc
  labels:
    app: nextcloud
spec:
  storageClassName: pv1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  selector:
    matchLabels:
      app: nextcloud