apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
  labels:
    app: nextcloud
spec:
  storageClassName: nextcloud-data
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/k3s/data"