apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-apps-pv
  labels:
    app: nextcloud
spec:
  storageClassName: nextcloud-apps
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/k3s/apps"